## example config input
## Dqmc Coniguration file with toml


[Model]
    # supported model types: RepulsiveHubbard and AttractiveHubbard 
    type = "AttractiveHubbard"

    [Model.Params]
    hopping_t = 1.0
    onsite_u = 4.0
    chemical_potential = 0.0

[Lattice]
    # support lattice type: Square, Cubic and Honeycomb(todo)
    type = "Square"
    cell = [ 4, 4 ]

    # symmetric points in the reciprocal lattice ( k stars )
    # for 2d square lattice, the following options are supported
    #   1. GammaPoint, XPoint, MPoint for high symmetry momentum points
    #   2. DeltaLine, ZLine, SigmaLine, Gamma2X2M2GammaLoop for high symmetry lines
    #   3. KstarsAll for all inequivalent momentum points
    #
    # for 3d cubic lattice, the following options are supported
    #   1. GammaPoint, XPoint, MPoint, RPoint for high symmetry momentum points
    #   2. DeltaLine, ZLine, SigmaLine, LambdaLine, SLine and TLine for high symmetry lines
    #   3. KstarsAll for all inequivalent momentum points
    momentum = "MPoint"
    momentum_list = "KstarsAll"

[CheckerBoard]
    # checkerboard break-ups, currently only supported for 2d square lattice
    whether_or_not = false

[MonteCarlo]
    beta = 8.0
    time_size = 160
    stabilization_pace = 10

[Measure]
    sweeps_warmup = 512
    bin_num = 20
    bin_size = 100
    sweeps_between_bins = 20
    
    # Supported physical observables for dqmc measurements
    #   1. filling_number                   (equal-time)
    #   2. double_occupancy                 (equal-time)
    #   3. kinetic_energy                   (equal-time)
    #   4. momentum_distribution            (equal-time)
    #   5. local_spin_corr                  (equal-time)
    #   6. spin_density_structure_factor    (equal-time)
    #   7. charge_density_structure_factor  (equal-time)
    #   8. s_wave_pairing_corr              (equal-time)
    #   9. greens_functions                 (dynamical)
    #  10. density_of_states                (dynamical)
    #  11. superfluid_stiffness             (dynamical, and only for 2d square lattice)
    #  12. dynamic_spin_susceptibility      (dynamical)
    
    # option 'all/All'  : measure all supported observables
    # option 'none/None': measure nothing
    observables = [ "all" ]
