name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Cache packages
      uses: actions/cache@v4
      with:
        path: ./apt-cache
        key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/ci.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install dependencies
      run: |
        if ls ./apt-cache/*.deb >/dev/null 2>&1; then
          sudo dpkg -i ./apt-cache/*.deb || sudo apt-get -f install -y
        else
          sudo apt-get update || true
          sudo apt-get install -y --no-install-recommends \
            ninja-build clang libboost-all-dev libeigen3-dev libopenblas-dev liblapacke-dev
          mkdir -p ./apt-cache
          sudo cp -a /var/cache/apt/archives/*.deb ./apt-cache/ || true
        fi

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: '3.21.x'

    - name: Configure CMake
      run: |
        cmake -S . -B build-debug-clang -G Ninja \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -Wpedantic" \
        -DCMAKE_CXX_FLAGS_DEBUG="-O2 -fsanitize=address,undefined -fsanitize-address-use-after-scope -fno-sanitize-recover=address,undefined -stdlib=libstdc++" \
        -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined"

    - name: Build
      run: cmake --build build-debug-clang --verbose --config Debug

    - name: Show help message
      run: ./build-debug-clang/main --help

    - name: Run with default parameters
      run: ./build-debug-clang/main